// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/adapters/sms"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/adapters/smtp"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/configs"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/errors"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/health_check"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/notify"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/handlers/ready_check"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/router"
	"github.com/WildEgor/e-shop-fiber-microservice-boilerplate/internal/services/template"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*Server, error) {
	configurator := configs.NewConfigurator()
	appConfig := configs.NewAppConfig(configurator)
	errorsHandler := error_handler.NewErrorsHandler()
	privateRouter := router.NewPrivateRouter()
	healthCheckHandler := health_check_handler.NewHealthCheckHandler()
	readyCheckHandler := ready_check_handler.NewReadyCheckHandler()
	publicRouter := router.NewPublicRouter(healthCheckHandler, readyCheckHandler)
	swaggerRouter := router.NewSwaggerRouter()
	smtpConfig := configs.NewSMTPConfig(configurator)
	smtpAdapter := smtp_adapter.NewSMTPAdapter(smtpConfig)
	smsConfig := configs.NewSMSConfig(configurator)
	smsAdapter := sms_adapter.NewSMSAdapter(smsConfig)
	templateService := template.NewTemplateService()
	notifyHandler := notify_handler.NewNotifyHandler(smtpAdapter, smsAdapter, templateService)
	amqpConfig := configs.NewAMQPConfig(configurator)
	amqpRouter := router.NewAMQPRouter(appConfig, notifyHandler, amqpConfig)
	server := NewApp(appConfig, errorsHandler, privateRouter, publicRouter, swaggerRouter, amqpRouter)
	return server, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
